# Generated by Django 4.1.13 on 2025-05-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_barcode', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_data',
            },
        ),
    ]
