# Generated by Django 4.1.13 on 2025-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_productdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='item_name_ascii',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
